### PR TITLE
fixed datatable view in admin list pages - for Meteor 1.2

### LINKED ISSUE #280: Exception from Tracker recompute function: TypeError: Cannot convert undefined or null to object
after update to 1.2., whenever i try and open any collection view from the dashboard i get:

bildschirmfoto 2015-09-28 um 15 25 06

any ideas?

### PR DESCRIPTION
**Pull request by CaptainN**
Fixed the error on datatable views (list pages) in Meteor 1.2. Fixes #280 (and #277).

### CODE REVIEW

**Comment by CaptainN** [comment]
I rebased to take care of that conflict.

**Comment by CaptainN** [comment]
As of this PR the user table is still empty (but it's a different error).

**Comment by mpowaga** [comment]
Thanks for PR! We made these changes in other commits.

**Comment by CaptainN** [comment]
Have the empty user tables been fixed in those other commits (when the accounts-ui is set to use USERNAME only)? My patch fixes that, and I'd be happy to make another pull request if you need.

**Pull request closed without merging**
