### PR TITLE
More missing slashes

### PR DESCRIPTION
**Pull request by RobertLowe**

### CODE REVIEW

**Comment by rzurawicki** [comment]
@msamoylov This PR uses proper HTML5 syntax

**Comment by msamoylov** [comment]
@rzurawicki no, sir. 

"A void element is an element whose content model never allows it to have contents under any circumstances. Void elements can have attributes.

The following is a complete list of the void elements in HTML:

area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr"

See:

1. http://blog.teamtreehouse.com/to-close-or-not-to-close-tags-in-html5
2. https://developer.mozilla.org/en/docs/Web/HTML/Element/Input#Examples
3. http://www.w3.org/TR/html-markup/syntax.html

**Comment by rzurawicki** [comment]
I'm confused.

Your sources say both style are valid 
```
<input>
<input />
```

Either both works. Am I understanding you correctly?

I see both styles are used in this codebase. I would suggest the maintainer decides on only one style to follow.

**Comment by msamoylov** [comment]
As per standard void tags shouldn't be closed.

**Comment by RobertLowe** [comment]
F#^k I started something here...

http://www.w3.org/TR/html5/syntax.html#start-tags

> Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single "/" (U+002F) character. This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

It's optional, but valid syntax, since HTML5 remains backwards compatible with HTML/XHTML.

My opinions on the matter are that one is explicit, so a developer (even a novice one), know what's happening. No knowledge of void tags required, so it improves readability by informing one that this is indeed a self-closing tag. 

Just my two cents, I have no strong preferences if this is closed or open. It's an unresolved best practise. I'd prefer the "old" way. ;)

**Pull request merged**
