### PR TITLE
fixes the various table view problems (including users)

### PR DESCRIPTION
**Pull request by CaptainN**
Also added an explicit "use" for the "check" package in package.js

### CODE REVIEW

**Comment by richardgsands** [comment]
Thanks @CaptainN (and thanks @yogiben for a great package)

+1 for pull request!

**Comment by nickpolet** [comment]
+1 for pull request. This fixes the error 'No data available in table' issue that many people seem to get. Can we see this added sometime soon?

**Comment by CaptainN** [comment]
You can download my fork to your local packages directory in the mean time.

**Comment by nickpolet** [comment]
@CaptainN Is there a nice way of doing this? Which folder does this go into and is it the full 'meteor-admin' folder that goes in it?

**Comment by CaptainN** [comment]
Create a "packages" folder in the root of your project, then copy my fork (or clone, or whatever) to "meteor-admin" in that folder. Meteor will use whatever version you have there instead of the one in the packages directory.

**Comment by rikonor** [comment]
@yogiben Any chance of merging this PR?

**Comment by eliasthompson** [comment]
Also tagging @mpowaga since he seems to be doing the merging these days.

**Comment by mpowaga** [comment]
We already made these changes in other commits. Thanks for PR anyway!

**Pull request closed without merging**
